### PR TITLE
Rethinking_2 Chp 6,7,8,9 conversion to PyMC v4

### PR DESCRIPTION
**Pull request by yahrMason**
- added tqdm to environment
- re-executed Chp 06 (there was a residual error message in the logs from the old code)
- updating Chp 07

# Thank you for opening a pull request!

Please check our [style guide](https://docs.pymc.io/en/latest/contributing/jupyter_style.html), and also make sure that the notebooks you've modified pass the `pre-commit` checks. If, for example, you modified `notebook1.ipynb` and `notebook2.ipynb`, you could do this by running:

```bash
pre-commit run --files notebook1.ipynb notebook2.ipynb
```

You may need to run it a couple of times before all the checks pass.

### CODE REVIEW

**Comment by canyon289** [comment]
Thank you!

**Comment by EAly** [comment]
<p>Thanks a lot @yahrMason. </p><p>I wonder if you already converted chapter 11?</p>

**Comment by yahrMason** [comment]
@EAly 

I have not gotten to chapter 11 yet, I am still working through chapter 10. I can take a look today though, I have picked up a few patterns of syntax that needs to be changed. Perhaps I can turn it around fairly quickly. I will let you know what I uncover.

**Comment by EAly** [comment]
Thanks a lot @yahrMason , totally appreciate your help!

**Comment by EAly** [comment]
<p>Awesome, thanks a lot!</p>

**Comment by yahrMason** [comment]
@EAly 
I updated the Chp11 code. I couldn't figure out the new arviz command for hpd (its hdi). I used a normal approximation to get around that and make the plots. I have made the change to hdi. I also made updates to 12 and 13.

**Comment by EAly** [comment]
Thanks a lot mate.

**Pull request merged**
