### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by vanislekahuna**
I paraphrased Prof. McElreath's video lecture and textbook explanations on Ch 1 (.md file) & Ch 2 in the notebook. The original code from the notebooks was left untouched. Please let me know if you'd like me to make any changes on the content, formatting etc.

# Thank you for opening a pull request!

Please check our [style guide](https://docs.pymc.io/en/latest/contributing/jupyter_style.html), and also make sure that the notebooks you've modified pass the `pre-commit` checks. If, for example, you modified `notebook1.ipynb` and `notebook2.ipynb`, you could do this by running:

```bash
pre-commit run --files notebook1.ipynb notebook2.ipynb
```

You may need to run it a couple of times before all the checks pass.

### CODE REVIEW

**Comment by canyon289** [comment]
@vanislekahuna I'm going to say two things that may sound contradictory so if its confusing I'm happy to clarify

1. These notes are great, you should publish them publicly
2. This repository is not the right place

Here's why. This repository currently is just the code translations for Rethinking, which makes it fairly simple to maintain and also makes it clear that if folks want an explanation or summary of the material they should go elsewhere

If we merge in summarization two things happen. First the scope of the repo expands, and the second is the pymc core team is now responsible for maintaining the summarization. Lets say if a new edition comes out then thered be an implicit expectation the summaries are updated or added.

That being said these summaries are super useful! Have you thought of hosting them on your own blog or in github repo hosted in your own namespace? If either of these sound interesting and you want to chat through it let me know!

And most of all, thank you for contributing to PyMC. I hope this doesnt scare you off

**Comment by vanislekahuna** [comment]
Hey @canyon289 , thanks for reviewing my work and getting back to me!

No worries, I understand your explanation. I just thought I'd offer my notes to the pymc-resources repo as a way for this info to get more exposure since this would typically be the default Github page for Python users to go if they want to learn and run the code for McElreath's Statistical Rethinking textbook. I'd be happy to continue running this project in my own repo and releasing blogs as I read through the book. 

My goal with these notes were to concretely learn Bayesian statistics by being able to re-summarize my thoughts on the subject to other learners via contributing to open-source. That said, if you have another way I can contribute while learning Bayesian statistics, I'd definitely be open to any suggestions! This is my first foray into probabilistic programming which is why I don't think there's too much I can contribute in terms of code but I can try  my hand at tackling any documentation tasks that might pop up. Let me know!

**Comment by canyon289** [comment]
Ill share some notes below, but first and foremost I love that you're wanting to give back to the community.

Heres some avenues
* Join the hackathon happening soon https://www.meetup.com/pymc-online-meetup/events/289450058/. Its meant for more advanced folks but it really cant hurt to show up and see what others are doing
* Submit a proposal to PyMCon (www.pymcon.com). A great idea may be a "Getting started with Bayes Session" where you share what youre using to learn with others who are starting to learn. 
* Keep an eye on beginner friendly issuse https://github.com/pymc-devs/pymc/issues?q=is%3Aopen+is%3Aissue+label%3A%22beginner+friendly%22

This is all of course in addition my suggestion of you sharing your notes with others

**Comment by vanislekahuna** [comment]
Awesome, thanks so much for the suggestions @canyon289 ! I didn't know about some of these resources so I'll definitely take advantage of them. And I'd like to be able to tackle some of these beginner issues on PyMC in the near future. Thanks again for the guidance.

**Pull request closed without merging**
