### PR TITLE
Lectures

### PR DESCRIPTION
**Pull request by benslack19**
Adding lecture 6 to repo.

### CODE REVIEW

**Comment by benslack19** [comment]
FYI the conflict is because of the Lecture 4 notebook output. In my original commit, I had forgotten to re-run the whole notebook so that the output of all cells is clean. It's corrected here in this new commit, along with Lecture 6 code.

**Comment by benslack19** [comment]
Hi @canyon289 or @MarcoGorelli, sorry for the bother, but could I please ask one of you to check out or approve this? I'm hoping we can publicize this and recruit contributors before McElreath starts the [next iteration of his course](https://github.com/rmcelreath/stat_rethinking_2023) which starts in a few weeks.

**Review by canyon289 — APPROVED** [review]

**Comment by canyon289** [comment]
thanks for adding these!

**Comment by benslack19** [comment]
> thanks for adding these!

Thank you @canyon289! does someone else need to merge the pull request? For the conflicting file, the new commit is a cleaner notebook for lecture 4, showing all code output.

**Comment by canyon289** [comment]
it can't be merged with conflicts. You'll need to rebase or open a new or where the changes are made on top of the current git head

**Comment by benslack19** [comment]
> it can't be merged with conflicts. You'll need to rebase or open a new or where the changes are made on top of the current git head

Ah ok, my bad! Thanks for your patience in explaining that to me. I'll correct this.

**Comment by canyon289** [comment]
All good. The easiest thing to do is probably create another branch from main, copy these to files on top, and make another PR.

Git and notebooks is miserable so if you try a merge or rebase it may be very painful.

**Pull request closed without merging**
